---
# Tasks file for dovecot
- name: Install packages
  apt:
    state: latest
    pkg:
      - dovecot-core
      - dovecot-imapd
      - dovecot-lmtpd
      - dovecot-mysql
      - dovecot-sieve
      - dovecot-managesieved
    update_cache: yes

- name: Delete default config
  file:
    state: absent
    path: /etc/dovecot/

- name: Create config directory
  file:
    path: /etc/dovecot
    state: directory

- name: Template dovecot.conf
  template:
    src: templates/dovecot.j2
    dest: /etc/dovecot/dovecot.conf
    mode: "0644"

- name: Generate Diffie-Hellman certificate
  command:
    argv:
      - openssl
      - dhparam
      - -out
      - /etc/dovecot/dh.pem
      - 4096
    creates: /etc/dovecot/dh.pem
  tags: dovecot_dh

- name: Template dovecot-sql.conf
  template:
    src: templates/dovecot-sql.j2
    dest: /etc/dovecot/dovecot-sql.conf
    mode: "0440"

- name: Copy spam-global.sieve
  copy:
    src: files/spam-global.sieve
    dest: /var/vmail/sieve/global/spam-global.sieve
    owner: vmail
    group: vmail
    mode: "0644"

- name: Copy learn-spam.sieve
  copy:
    src: files/learn-spam.sieve
    dest: /var/vmail/sieve/global/learn-spam.sieve
    owner: vmail
    group: vmail
    mode: "0644"

- name: Copy learn-ham.sieve
  copy:
    src: files/learn-ham.sieve
    dest: /var/vmail/sieve/global/learn-ham.sieve
    owner: vmail
    group: vmail
    mode: "0644"
