---
# Tasks file for rspamd
- name: Install packages
  apt:
    state: latest
    pkg:
      - rspamd
    update_cache: yes

- name: Install packages
  apt:
    state: latest
    pkg:
      - rspamd
      - redis-server
    update_cache: yes

- name: Hash rspamd password
  command:
    argv:
      - rspamadm
      - pw
      - -p
      - "{{ rspamd_password }}"
      - -e
  register: rspamd_hash_output
  tags: rspamd_password

- name: Template worker-controller.inc
  template:
    src: templates/worker-controller.j2
    dest: /etc/rspamd/local.d/worker-controller.inc
  tags: rspamd_password

- name: Copy classifier-bayes.conf
  copy:
    src: files/classifier-bayes.conf
    dest: /etc/rspamd/local.d/classifier-bayes.conf

- name: Copy logging.inc
  copy:
    src: files/logging.inc
    dest: /etc/rspamd/local.d/logging.inc

- name: Copy milter_headers.conf
  copy:
    src: files/milter_headers.conf
    dest: /etc/rspamd/local.d/milter_headers.conf

- name: Copy options.inc
  copy:
    src: files/options.inc
    dest: /etc/rspamd/local.d/options.inc

- name: Copy worker-proxy.inc
  copy:
    src: files/worker-proxy.inc
    dest: /etc/rspamd/local.d/worker-proxy.inc

- name: Copy worker-normal.inc
  copy:
    src: files/worker-normal.inc
    dest: /etc/rspamd/local.d/worker-normal.inc

- name: Create directory for dkim
  file:
    path: /var/lib/rspamd/dkim/
    state: directory
    owner: _rspamd
    group: _rspamd
    mode: "0540"

- name: Create keys
  command:
    argv:
      - rspamadm
      - dkim_keygen
      - -b
      - 2048
      - -s
      - mail
      - -d
      - "{{ domain }}"
      - -k
      - /var/lib/rspamd/dkim/{{ domain }}.mail.key
    creates: /var/lib/rspamd/dkim/{{ domain }}.mail.key
  register: key_output
  tags: dkim_keys

- name: Write out DNS info
  copy:
    content: "{{ key_output.stdout }}"
    dest: "/var/lib/rspamd/dkim/{{ domain }}.mail.pub"
  when: key_output.changed
  tags: dkim_keys

- name: Copy arc.conf
  copy:
    src: files/arc.conf
    dest: /etc/rspamd/local.d/arc.conf
    owner: _rspamd
    group: _rspamd
    mode: "0440"

- name: Copy dkim_signing.conf
  copy:
    src: files/dkim_signing.conf
    dest: /etc/rspamd/local.d/dkim_signing.conf
    owner: _rspamd
    group: _rspamd
    mode: "0440"

- name: Copy redis.conf
  copy:
    src: files/redis.conf
    dest: /etc/rspamd/local.d/redis.conf
    owner: _rspamd
    group: _rspamd
    mode: "0440"

- name: Reload Rspamd
  command: systemctl reload rspamd
